import type { Track } from '@/features/player/model/playerTypes'

const demoCoverImage = '/covers/album-cover.png'

export const demoTracks: Track[] = [
  {
    id: 'morning-signal',
    title: 'Morning Signal',
    artist: 'Lin Chen',
    album: 'Desk Light Sessions',
    category: 'Desk Light',
    durationSeconds: 214,
    coverTone: 'lagoon',
    coverImage: demoCoverImage,
    lyrics: [
      { id: 'm1', timeSeconds: 0, original: 'Morning light is moving through the room.', translation: '晨光正缓缓穿过房间' },
      { id: 'm2', timeSeconds: 28, original: 'Every quiet signal leads me home.', translation: '每个安静的信号都带我回家' },
      { id: 'm3', timeSeconds: 58, original: 'Side by side, we let the city fade.', translation: '并肩看着城市慢慢隐去' },
      { id: 'm4', timeSeconds: 88, original: 'Keep this little rhythm close tonight.', translation: '今夜把这段节奏留在身边' },
      { id: 'm5', timeSeconds: 118, original: 'The curtains breathe in amber lines.', translation: '窗帘在琥珀色光线里轻轻呼吸' },
      { id: 'm6', timeSeconds: 148, original: 'Your voice turns static into signs.', translation: '你的声音把杂讯变成讯号' },
      { id: 'm7', timeSeconds: 176, original: 'The morning signal starts again.', translation: '晨间讯号再次响起' },
    ],
  },
  {
    id: 'glass-station',
    title: 'Glass Station',
    artist: 'North Arcade',
    album: 'Transit Notes',
    category: 'Transit',
    durationSeconds: 188,
    coverTone: 'violet',
    coverImage: demoCoverImage,
    lyrics: [
      { id: 'g1', timeSeconds: 0, original: 'Waiting where the glass trains meet.', translation: '在玻璃列车交汇处等待' },
      { id: 'g2', timeSeconds: 26, original: 'Neon names drift under our feet.', translation: '霓虹名字从脚下流过' },
      { id: 'g3', timeSeconds: 52, original: 'Your reflection leans into mine.', translation: '你的倒影轻轻靠近我的倒影' },
      { id: 'g4', timeSeconds: 78, original: 'The timetable forgets the time.', translation: '时刻表忘记了时间' },
      { id: 'g5', timeSeconds: 104, original: 'No destination, only tonight.', translation: '没有终点，只有今晚' },
      { id: 'g6', timeSeconds: 134, original: 'We count the sparks along the line.', translation: '我们数着轨道旁的微光' },
      { id: 'g7', timeSeconds: 162, original: 'The station disappears in light.', translation: '车站消失在光里' },
    ],
  },
  {
    id: 'quiet-magnet',
    title: 'Quiet Magnet',
    artist: 'Mira Vale',
    album: 'Small Room Weather',
    category: 'Desk Light',
    durationSeconds: 241,
    coverTone: 'rose',
    coverImage: demoCoverImage,
    lyrics: [
      { id: 'q1', timeSeconds: 0, original: 'A quiet magnet pulls the rain.', translation: '安静的磁场牵引着雨' },
      { id: 'q2', timeSeconds: 34, original: 'Small room weather knows my name.', translation: '小房间的天气记得我的名字' },
      { id: 'q3', timeSeconds: 68, original: 'The kettle hums a silver tune.', translation: '水壶哼着银色的小调' },
      { id: 'q4', timeSeconds: 102, original: 'Soft clouds gather near the moon.', translation: '柔软的云聚在月亮旁' },
      { id: 'q5', timeSeconds: 136, original: 'Stay until the window turns to blue.', translation: '留下直到窗外变成蓝色' },
      { id: 'q6', timeSeconds: 170, original: 'Every wall is listening too.', translation: '每一面墙也都在倾听' },
      { id: 'q7', timeSeconds: 205, original: 'Every compass points to you.', translation: '每只罗盘都指向你' },
    ],
  },
  {
    id: 'silver-courtyard',
    title: 'Silver Courtyard',
    artist: 'The Window Maps',
    album: 'Late Geometry',
    category: 'Transit',
    durationSeconds: 263,
    coverTone: 'amber',
    coverImage: demoCoverImage,
    lyrics: [
      { id: 's1', timeSeconds: 0, original: 'Silver shadows cross the courtyard.', translation: '银色影子穿过庭院' },
      { id: 's2', timeSeconds: 38, original: 'Late geometry holds the stars.', translation: '迟来的几何托住星光' },
      { id: 's3', timeSeconds: 74, original: 'Your footsteps sketch another square.', translation: '你的脚步又画出一个方格' },
      { id: 's4', timeSeconds: 110, original: 'The night folds softly in the air.', translation: '夜色在空气里轻轻折叠' },
      { id: 's5', timeSeconds: 146, original: 'Count the windows, count the hours.', translation: '数着窗户，也数着时光' },
      { id: 's6', timeSeconds: 184, original: 'Quiet bells bloom into flowers.', translation: '安静的钟声开成花' },
      { id: 's7', timeSeconds: 224, original: 'We are never very far.', translation: '我们从未相距太远' },
    ],
  },
  {
    id: 'afterimage-loop',
    title: 'Afterimage Loop',
    artist: 'Yun River',
    album: 'Soft Circuit',
    category: 'Afterimage',
    durationSeconds: 197,
    coverTone: 'blue',
    coverImage: demoCoverImage,
    lyrics: [
      { id: 'a1', timeSeconds: 0, original: 'Afterimages circle in the dark.', translation: '残像在黑暗里回旋' },
      { id: 'a2', timeSeconds: 28, original: 'Soft circuits flicker into sparks.', translation: '柔软电路闪成火花' },
      { id: 'a3', timeSeconds: 56, original: 'Your outline hums behind my eyes.', translation: '你的轮廓在我眼后低鸣' },
      { id: 'a4', timeSeconds: 84, original: 'Blue echoes climb the power lines.', translation: '蓝色回声爬上电线' },
      { id: 'a5', timeSeconds: 112, original: 'Let the loop remember us.', translation: '让循环记住我们' },
      { id: 'a6', timeSeconds: 140, original: 'Hold the pulse and let it trust.', translation: '握住脉冲，让它学会相信' },
      { id: 'a7', timeSeconds: 168, original: 'Begin again without a rush.', translation: '不慌不忙，再次开始' },
    ],
  },
]
