export const appCopy = {
  productName: 'SpMusic',
  appTitle: 'SpMusic 播放界面',
  appIntro: '本地优先、轻量安静的桌面音乐播放界面。',
  shellLabel: 'SpMusic 最小播放界面',
  nowPlaying: {
    eyebrow: '正在播放',
    emptyTitle: '暂无当前歌曲',
    emptyDescription: '歌曲列表为空时，播放器会保持安全的空状态。',
    artistLabel: '艺术家',
    albumLabel: '专辑',
    durationLabel: '时长',
  },
  controls: {
    openAudio: '打开音频',
    previous: '上一首',
    play: '播放',
    pause: '暂停',
    next: '下一首',
    like: '喜欢',
    dislike: '不喜欢',
    more: '更多',
    shuffle: '随机播放',
    shuffleOff: '关闭随机播放',
    shuffleCategoryOrder: '按分类顺序随机播放分类内歌曲',
    shuffleCategoryRandom: '随机播放分类，分类内顺序播放',
    repeat: '列表循环',
    repeatOne: '单曲循环',
    sequential: '顺序播放',
    playAllCategories: '播放当前分类并停止',
    captions: '桌面字幕',
    captionsUnavailable: '桌面字幕暂未接入',
    volume: '音量',
    queue: '播放列表',
    collapse: '收起',
    fullscreen: '全屏',
    minimize: '最小化',
    maximize: '最大化',
    restore: '还原',
    settings: '设置',
    close: '关闭',
  },
  settings: {
    title: '设置',
    description: '管理播放器界面入口和外观。',
    on: '开启',
    off: '关闭',
    theme: {
      title: '主题管理',
      description: '打开主题工作室，管理内置和用户主题。',
    },
  },
  volume: {
    label: '音量',
    groupLabel: '音量控制',
    value: (volume: number) => `${Math.round(volume)}%`,
  },
  lyrics: {
    title: '歌词',
    empty: '未找到歌词',
    emptyTitle: '未找到歌词',
    emptyDescription: '可在第三方应用搜索歌词',
    openExternalApp: '打开歌词应用',
    openExternalAppUnavailable: '歌词应用入口暂不可用',
    settingsUnavailable: '歌词设置入口暂不可用',
  },
  moreMenu: {
    title: '更多操作',
    copyTitle: '复制歌曲名',
    copiedTitle: '已复制歌曲名',
    copyUnavailable: '当前环境无法复制歌曲名',
    unavailable: '暂不可用',
    delete: '删除',
    playlist: '播放列表',
    bookmark: '书签',
    cover: '专辑封面',
    info: '信息 / 标签',
    listeningHistory: '收听记录',
    artist: '艺术家',
    album: '专辑',
    folder: '文件夹',
    genre: '流派',
  },
  progress: {
    label: '播放进度',
    elapsed: '已播放',
    total: '总时长',
  },
  playbackInfo: {
    label: '播放输出信息（演示数据）',
    output: 'OPENSL ES OUTPUT 16 BIT 48 KHZ',
  },
  audio: {
    statusLabel: '真实播放状态',
    idle: '真实音频后端空闲',
    loading: '正在加载音频…',
    ready: (fileName: string) => `已加载：${fileName}`,
    playing: (fileName: string) => `真实播放中：${fileName}`,
    paused: (fileName: string) => `已暂停：${fileName}`,
    stopped: (fileName: string) => `已停止：${fileName}`,
    ended: (fileName: string) => `播放结束：${fileName}`,
    unavailable: '真实播放后端不可用，请在 Tauri 桌面端验证。',
    errors: {
      USER_CANCELLED: '已取消选择音频。',
      NO_TRACK_LOADED: '还没有加载音频，请先打开一个本地音频文件。',
      INVALID_PATH: '音频路径无效。',
      FILE_NOT_FOUND: '找不到这个音频文件。',
      UNREADABLE_FILE: '无法读取这个音频文件。',
      UNSUPPORTED_FORMAT: '暂不支持这个音频格式。',
      PLAYBACK_INIT_FAILED: '音频输出初始化失败。',
      PLAYBACK_FAILED: '播放失败。',
      UNSUPPORTED_OPERATION: '当前播放后端暂不支持这个操作。',
      INVALID_VOLUME: '音量值无效。',
      INTERNAL_ERROR: '音频后端内部错误。',
    },
  },
  queue: {
    title: '播放队列',
    description: '当前会话中的本地音频。',
    current: '当前',
    emptyTitle: '尚未打开音频',
    emptyDescription: '使用下方的打开音频按钮选择本地文件或播放列表。',
  },
} as const
