import type { AppearancePreset } from './appearanceTypes'

export const defaultAppearance: AppearancePreset = {
  id: 'default',
  name: 'SpMusic Default',
  colorSchemes: {
    light: {
      background: '#f7f8f4',
      surface: '#ffffff',
      surfaceMuted: '#eef3ec',
      text: '#4f5661',
      textMuted: '#707985',
      textStrong: '#101317',
      border: '#d9ded6',
      accent: '#0f8b7f',
      accentSoft: '#dff3ee',
      accentContrast: '#ffffff',
      playerBlue: '#276389',
      playerBlueSoft: '#cae6ff',
      playerBlueInk: '#276389',
      playerInk: '#17212b',
      playerMuted: '#72777f',
      playerLyrics: '#151619',
      playerOverlay: '#AAA7B5',
      playerDock: '#f7f9ff',
      playerSurfaceVariant: '#dde3ea',
      playerProgressPlayed: '#276389',
      playerProgressUnplayed: '#c1c7ce',
    },
    dark: {
      background: '#101514',
      surface: '#181f1d',
      surfaceMuted: '#222b28',
      text: '#d4ddda',
      textMuted: '#94a19d',
      textStrong: '#f7fbfa',
      border: '#35413d',
      accent: '#5bc7b8',
      accentSoft: '#1d4841',
      accentContrast: '#09201d',
      playerBlue: '#78bde7',
      playerBlueSoft: '#1f4055',
      playerBlueInk: '#bfe6ff',
      playerInk: '#f5f9fb',
      playerMuted: '#a0abb0',
      playerLyrics: '#a0abb0',
      playerOverlay: '#0a1111cc',
      playerDock: '#15201f',
      playerSurfaceVariant: '#dde3ea',
      playerProgressPlayed: '#78bde7',
      playerProgressUnplayed: '#c1c7ce',
    },
  },
  radii: {
    sm: '6px',
    md: '8px',
    lg: '12px',
    pill: '999px',
  },
  motion: {
    level: 'subtle',
    durationScale: 1,
    easing: 'cubic-bezier(.65, 0, .35, 1)',
  },
  typography: {
    fontFamily: 'geist',
    fontScale: 1,
  },
  components: {
    surface: 'glass',
    buttons: 'soft',
    windowControls: 'standard',
  },
  player: {
    backgroundEffect: 'cover-ambient',
    backgroundBlur: 100,
    backgroundBrightness: 68,
    backgroundSaturation: 165,
    backgroundMaskOpacity: 14,
    backgroundVignette: 72,
    coverRadius: 38,
    coverShadow: 74,
    lyricsFontScale: 1.4,
    lyricsTightSpacing: 0,
    lyricsNormalSpacing: 53,
    lyricsTightThresholdSeconds: 15.5,
    activeLyricEmphasis: 'combined',
    controls: {
      material: 'inherit',
      radius: 50,
      shadow: 50,
      density: 'standard',
      primaryButton: { style: 'filled', sizeScale: 100 },
      auxiliaryButtons: { style: 'tiered' },
      progress: { trackThickness: 6, thumbSize: 27 },
      visibility: { timeLabels: true, volumePercent: true },
    },
    trackMetadata: {
      titleMaxWidth: 420,
      detailsMaxWidth: 680,
      scrollPixelsPerSecond: 32,
      scrollStartDelayMs: 2000,
      scrollEdgePauseMs: 3000,
    },
  },
  icons: {
    provider: 'default',
  },
  advanced: {
    customCss: '',
  },
  experimental: {
    layoutCss: '',
    resources: [],
  },
  metadata: {
    tier: 'standard',
    author: 'SpMusic',
    description: 'SpMusic 默认浅色与深色主题',
    capabilities: ['tokens'],
    riskAcknowledged: false,
  },
}
